# =========================================================
# 4. SERVICES: Acceso y DNS Interno
# =========================================================

# Servicio APP (Web - Puerto 8080)
apiVersion: v1
kind: Service
metadata: { name: app-service } # Nombre interno: 'app-service'
spec:
  selector: { app: web }
  ports: [{ port: 80, targetPort: 80 }]
  type: NodePort # Expone la app al exterior
---
# Servicio AUTH (Autenticación - Puerto 8082)
apiVersion: v1
kind: Service
metadata: { name: auth-service } # Nombre interno: 'auth-service'
spec:
  selector: { app: auth }
  ports: [{ port: 80, targetPort: 80 }]
  type: NodePort # Expone el login/registro al exterior
---
# Servicio DB (Acceso interno)
apiVersion: v1
kind: Service
metadata: { name: db-service } # Nombre interno: 'db-service'
spec:
  selector: { app: mysql }
  ports: [{ port: 3306, targetPort: 3306 }]
  type: ClusterIP # Solo accesible dentro del clúster (correcto para DB)
---
# Servicio PhpMyAdmin (Acceso a la interfaz de DB)
apiVersion: v1
kind: Service
metadata: { name: phpmyadmin-service }
spec:
  selector: { app: phpmyadmin }
  ports: [{ port: 80, targetPort: 80 }]
  type: NodePort
